# Generated by Django 3.1.7 on 2021-03-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=30)),
                ('cpf', models.CharField(default='', max_length=9)),
                ('telefone', models.CharField(default='', max_length=11)),
                ('nota', models.CharField(default='', max_length=3)),
                ('falta', models.CharField(default='', max_length=3)),
                ('status', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=30)),
                ('descricao', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=30)),
                ('dt_criacao', models.CharField(default='', max_length=10)),
                ('descricao', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
